### ISSUE TITLE
Typescript generator. Using allOf in an external reference produces RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by AlbinAndersson96** [asyncapi/modelina#1479]
#### Describe the bug
When using allOf in an external schema and referencing said schema from the root, it potentially throws the below error when generating with the default Typescript generator.
```
RangeError: Maximum call stack size exceeded
    at Function.values (<anonymous>)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:104:41)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
    at ConstrainedUnionModel.getNearestDependencies (<proj_root>\src\node_modules\@asyncapi\modelina\lib\cjs\models\ConstrainedMetaModel.js:112:35)
```

#### How to Reproduce
Generate models from the following spec files:

asyncapi.yaml
```
asyncapi: '2.6.0'
info:
  title: 'This is a title'
  version: '2.0.0'

channels:
  this/is/a/topic:
    publish:
      operationId: opId
      message:
        $ref: '#/components/messages/problemResponse'
  
components:
  messages:
    problemResponse:
      title: Problem Response
      contentType: application/problem+json
      payload:
        $ref: './problem.yaml#/parentProblems'
```

problem.yaml
```
parentProblems:
  x-parser-schema-id: problem
  oneOf:
    - $ref: '#/problem'
    - $ref: '#/parentProblems'
problem:
  x-parser-schema-id: problem
  type: object
  properties:
    type:
      type: string
      format: uri
  discriminator: '__extensionObjectType__'
```

#### Expected behavior
We expect the data models to generate, or alternatively throw an informative error if the use case isn't supported.

**Comment by jonaslagoni** [comment]
Another weird input is 
```yml 
asyncapi: '2.6.0'
info:
  title: 'Persistent Storage'
  version: '2.0.0'

channels:
  this/is/a/topic:
    publish:
      operationId: opId
      message:
        $ref: '#/components/messages/problemResponse'
  
components:
  messages:
    problemResponse:
      title: Problem Response
      contentType: application/problem+json
      payload:
        $ref: '#/components/schemas/parentProblems'
  schemas: 
    parentProblems:
      x-parser-schema-id: problem
      oneOf:
        - $ref: '#/components/schemas/problem'
        - $ref: '#/components/schemas/parentProblems'
    problem:
      x-parser-schema-id: problem
      type: object
      properties:
        type:
          type: string
          format: uri
```

Which outputs:
```
type ParentProblems = Problem | ;
class Problem {
  private _reservedType?: string;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    reservedType?: string,
    additionalProperties?: Map<string, any>,
  }) {
    this._reservedType = input.reservedType;
    this._additionalProperties = input.additionalProperties;
  }

  get reservedType(): string | undefined { return this._reservedType; }
  set reservedType(reservedType: string | undefined) { this._reservedType = reservedType; }

  get additionalProperties(): Map<string, any> | undefined { return this._additionalProperties; }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) { this._additionalProperties = additionalProperties; }
}
```

In the `next` branch at least.

**Comment by jonaslagoni** [comment]
@AlbinAndersson96 what is the expected output for this small example?

**Comment by AlbinAndersson96** [comment]
@jonaslagoni Probably something similar to this when generating with defaults. Can't remember if named exports is the default but if it isn't just replace my export with the default.

``` typescript
import Problem from './Problem';

type ParentProblem = Problem | ParentProblem; // Very unsure about this. A type referencing itself?
export { DssProblems };
```

``` typescript
class Problem {
  private _type?: string;

  constructor(input: {
    type?: string,
  }) {
    this._type = input.type;
  }

  get type(): string | undefined { return this._type; }
  set type(_type: string | undefined) { this._type= _type; }
}
export { Problem };

```

**Comment by AlbinAndersson96** [comment]
That said. The self-reference of ParentProblem is tripping me up a bit with how to actually generate it. This example also triggers the issue, without the self-reference.

asyncapi.yaml
``` typescript
asyncapi: '2.6.0'
info:
  title: 'This is a title'
  version: '2.0.0'

channels:
  this/is/a/topic:
    publish:
      operationId: opId
      message:
        $ref: '#/components/messages/problemResponse'
  
components:
  messages:
    problemResponse:
      title: Problem Response
      contentType: application/problem+json
      payload:
        $ref: './problem.yaml#/parentProblems'
```
problem.yaml
``` typescript
parentProblems:
  oneOf:
  - $ref: '#/problem'
  - $ref: '#/validationProblem'
problem:
  type: object
  properties:
    type:
      type: string
      format: uri
  discriminator: '__extensionObjectType__'
validationProblem:
  allOf:
    - $ref: '#/problem'
    - type: object
      properties:
        errors:
          type: object
          additionalProperties: true
```

**Comment by jonaslagoni** [comment]
Just encountered this problem, working on the fix "again" 🙃

**Comment by jonaslagoni** [comment]
Should be fixed as of v3 ✌️
