### ISSUE TITLE
Ensure consistancy between switch statements

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#236]
#### Reason/Context
Currently, we have very small switch statements which are considered a [code smell by sonarcloud](https://sonarcloud.io/project/issues?id=asyncapi_generator-model-sdk&open=AXjKlPuxVLGRvzF4eQNt&resolved=false&rules=typescript%3AS1301). We should fix all of these issues so we get rid of them.

Make sure to read the readme file [how to contribute](https://github.com/asyncapi/modelina#contributing), if you have any questions feel free to reach out here, or in our [Slack](https://www.asyncapi.com/slack-invite).

**Comment by Blakelist7** [comment]
Hey @jonaslagoni I would like to give this one a shot. I think using `if else` would be a better approach, right?

**Comment by jonaslagoni** [comment]
> Hey @jonaslagoni I would like to give this one a shot. I think using `if else` would be a better approach, right?

hey @Blakelist7, awesome 👍 Yes definitely agree. Feel free to ping me if you get stuck or have any questions 🙂

**Comment by Blakelist7** [comment]
Hey @jonaslagoni could you help me with these?
```
Summary of all failing tests
FAIL test/generators/java/presets/DescriptionPreset.spec.ts (9.355 s)
  ● JAVA_DESCRIPTION_PRESET › should render description and examples for enum

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -1,11 +1,11 @@
      /**
       * Description for enum
       * Examples: value
       */
      public enum Enum {
    -   ON("on"), OFF("off");
    +   ON(on), OFF(off);

        private String value;

        Enum(String value) {
          this.value = value;

      88 |
      89 |     const enumModel = await generator.renderEnum(model, inputModel);
    > 90 |     expect(enumModel).toEqual(expected);
         |                       ^
      91 |   });
      92 | });
      93 |

      at test/generators/java/presets/DescriptionPreset.spec.ts:90:23
      at fulfilled (test/generators/java/presets/DescriptionPreset.spec.ts:5:58)

FAIL test/generators/java/JavaGenerator.spec.ts (9.452 s)
  ● JavaGenerator › should render `enum` type (string type)

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -1,7 +1,7 @@
      public enum States {
    -   TEXAS("Texas"), ALABAMA("Alabama"), CALIFORNIA("California"), NEW_YORK("New York");
    +   TEXAS(Texas), ALABAMA(Alabama), CALIFORNIA(California), NEW_YORK(New York);

        private String value;

        States(String value) {
          this.value = value;

      150 |
      151 |     let enumModel = await generator.renderEnum(model, inputModel);
    > 152 |     expect(enumModel).toEqual(expected);
          |                       ^
      153 |
      154 |     enumModel = await generator.render(model, inputModel);
      155 |     expect(enumModel).toEqual(expected);

      at test/generators/java/JavaGenerator.spec.ts:152:23
      at fulfilled (test/generators/java/JavaGenerator.spec.ts:5:58)

  ● JavaGenerator › should render `enum` type (union type)

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -1,7 +1,7 @@
      public enum Union {
    -   TEXAS("Texas"), ALABAMA("Alabama"), NUMBER_0(0), NUMBER_1(1), BOOLEAN_TRUE(true);
    +   TEXAS(Texas), ALABAMA(Alabama), NUMBER_0(0), NUMBER_1(1), BOOLEAN_TRUE(true);

        private Object value;

        Union(Object value) {
          this.value = value;

      242 |
      243 |     let enumModel = await generator.renderEnum(model, inputModel);
    > 244 |     expect(enumModel).toEqual(expected);
          |                       ^
      245 |
      246 |     enumModel = await generator.render(model, inputModel);
      247 |     expect(enumModel).toEqual(expected);

      at test/generators/java/JavaGenerator.spec.ts:244:23
      at fulfilled (test/generators/java/JavaGenerator.spec.ts:5:58)

  ● JavaGenerator › should work custom preset for `enum` type

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -1,8 +1,8 @@
      @EnumAnnotation
      public enum CustomEnum {
    -   TEXAS("Texas"), ALABAMA("Alabama"), CALIFORNIA("California");
    +   TEXAS(Texas), ALABAMA(Alabama), CALIFORNIA(California);

        private String value;

        CustomEnum(String value) {
          this.value = value;

      300 |
      301 |     let enumModel = await generator.render(model, inputModel);
    > 302 |     expect(enumModel).toEqual(expected);
          |                       ^
      303 |
      304 |     enumModel = await generator.renderEnum(model, inputModel);
      305 |     expect(enumModel).toEqual(expected);

      at test/generators/java/JavaGenerator.spec.ts:302:23
      at fulfilled (test/generators/java/JavaGenerator.spec.ts:5:58)
```

**Comment by jonaslagoni** [comment]
@Blakelist7 it looks like some code was removed so enums no longer generate (gonna use the first error as example) `ON("on"), OFF("off");` but generates `ON(on), OFF(off);` where it is missing the `"`. Did you remove any logic here that should not be removed or changed somehow? 🤔 

Feel free to create a draft PR with the changes, then it is easier to spot whats wrong 🙂

**Comment by Blakelist7** [comment]
> @Blakelist7 it looks like some code was removed so enums no longer generate (gonna use the first error as example) `ON("on"), OFF("off");` but generates `ON(on), OFF(off);` where it is missing the `"`. Did you remove any logic here that should not be removed or changed somehow? thinking
> 
> Feel free to create a draft PR with the changes, then it is easier to spot whats wrong slightly_smiling_face

As far as I know, I don't think that I deleted some logic but it might have happened by mistake. I have raised a PR for more convenience, please have a look.
